In [1]:
import numpy as np

In [3]:
# 1. Buatlah array integer dari 10 sampai 50
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [4]:
# 2. Buatlah array integer dari 10 sampai 50 kelipatan 2
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [7]:
# 3. Buatlah data array 3 baris 3 kolom dari 0 sampai 8
np.arange(0, 9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# 4. Buatlah data array dengan nilai 25 data secara random
np.random.rand(25)

array([0.30751225, 0.43898555, 0.02301307, 0.03314667, 0.6949303 ,
       0.33377697, 0.08597329, 0.63428553, 0.29389404, 0.65480691,
       0.17888789, 0.95760564, 0.53153242, 0.6870246 , 0.10722412,
       0.2078883 , 0.6440652 , 0.48302626, 0.69553305, 0.45731761,
       0.5947105 , 0.5021115 , 0.56720028, 0.16081724, 0.5601954 ])

In [14]:
# 5. Buatlah data array seperti Gambar
arr = np.arange(1, 26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [16]:
# 6. Dari soal no 5 tampilkan data array seperti Gambar
arr[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
# 7. Dari soal no 5 tampilkan tampilkan angka 20
arr[3, 4]

20

In [18]:
# 8. Dari soal no 5 tampilkan data array seperti ini?

In [23]:
# 9. Dari soal no 5 tampilkan min, max, argmax, argmin nya
arr.min()

1

In [24]:
arr.max()

25

In [25]:
arr.argmax()

24

In [26]:
arr.argmin()

0

In [27]:
arr.sum()

325

In [37]:
# 10. Dari soal no 5 tampilkan index yang nilainya lebih dari 10 dan kurang sama dengan 20
newarr = arr[arr>10]
newarr[newarr<=20]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])